### ISSUE TITLE
external nav bar not persisting the ui-btn-active

### ISSUE THREAD

**Issue by navarrorc** [jquery/jquerymobile.com#101]
Hi.

The issue is that the ui-btn-active is not being applied to the selected button on the external navbar, even after following the documentation's instructions.

Please compare the following examples and test out their external navbar implementations:

working
http://demos.jquerymobile.com/1.4.2/toolbar-fixed-persistent/index.html

not working
http://demos.jquerymobile.com/1.4.3/toolbar-fixed-persistent/index.html

I spent many hours trying to figure out why the 1.4.3 version didn't behave as described in the documentation. I eventually ended up using version 1.4.2 and the ui-btn-active is applied to the selected tab button just as described in the documentation. Did something break in version 1.4.3?

**Comment by nutriapp** [comment]
Did you find a solution for this?

**Comment by arschmitz** [comment]
@navarrorc @nutriapp This is the repositiory for the jquerymobile.com website and its content not the jQuery Mobile Library. Please see http://github.com/jquery/jquery-mobile

**Comment by nutriapp** [comment]
This error it's shown in jquerymobile.com as well
