### ISSUE TITLE
Feature request: Ability to build custom Bower packages

### ISSUE THREAD

**Issue by frankie-loves-jesus** [jquery/jquerymobile.com#110]
An `Add as Bower` checkbox, registering ones custom build at http://bower.io/ as ie. `jquery-mobile-<version>-custom-<hex>`. Then, if other people build the same combo, they can just reuse that one.

An `Add as Rails Asset` checkbox (https://rails-assets.org/) would also be nice.

Thanks!

**Comment by arschmitz** [comment]
@frankie-loves-jesus I'm sorry but there is no way we will publish this many packages. This would cause an immense amount of pollution of the bower and rails-assets package libraries.

Closing as wont fix.

**Comment by frankie-loves-jesus** [comment]
> I'm sorry but there is no way we will publish this many packages. This would cause an immense amount of pollution of the bower and rails-assets package libraries.

Not all package combos are likely to be generated. In addition, Bower will soon allow authors to delete their own packages (https://github.com/bower/bower/issues/120). This way we could automatically purge older versions to keep things clean.

I don't see any other way as it's impossible to add the existing jQM Bower package and then cherrypick components via Sprockets (https://github.com/jquery/jquery-mobile/issues/7319 etc.). I reckon the majority of Rails devs would want to customize their jQM distributions.
