### ISSUE TITLE
Apps Section in Resources View redirects the same page

### ISSUE THREAD

**Issue by mappmechanic** [jquery/jquerymobile.com#112]
Whenever we click on an app in Resources View, it redirects to another page.

I think you should open the link in a _blank new tab so that the readers can open other apps also at the same time.

http://jquerymobile.com/resources/#Apps

**Comment by agcolom** [comment]
@arschmitz Please let me know if you'd like me to action with a PR.

**Comment by arschmitz** [comment]
@agcolom Please do!

**Comment by arthurvr** [comment]
We want this on every link on that page or only the for the `apps` section? I can PR this too if you want.

**Comment by arthurvr** [comment]
PR https://github.com/jquery/jquerymobile.com/pull/124. @agcolom WDYT?
