### ISSUE TITLE
Google CDN links are broken

### ISSUE THREAD

**Issue by coliff** [jquery/jquerymobile.com#118]
The Google CDN links do not work at: http://jquerymobile.com/download/

It looks like Google have not posted the latest jQuery Mobile releases to their CDN service.
https://developers.google.com/speed/libraries/devguide#jquerymobile

**Comment by jaspermdegroot** [comment]
@coliff 

What links do not work? I just tested all 1.4.5 links and they work fine. I don't see anything wrong/missing here either: https://developers.google.com/speed/libraries/devguide#jquerymobile

Closing for now, but please let us know if you still see a problem. Thanks!

**Comment by coliff** [comment]
Hi @jaspermdegroot - Google have literally just updated that page. Those links were broken a few days ago. Proof below in case you think I'm crazy (page grab from 1st March from Web Archive) :-)
http://web.archive.org/web/20150301130908/https://developers.google.com/speed/libraries/devguide#jquerymobile
