### ISSUE TITLE
add IOS8 to the browser support page

### ISSUE THREAD

**Issue by franckl** [jquery/jquerymobile.com#121]
http://jquerymobile.com/browser-support/1.4/ is not listing IOS8, is it on purpose ?

**Comment by arschmitz** [comment]
@franckl it was not yet out when we release 1.4.5 was tested against it though

**Comment by arthurvr** [comment]
> it was not yet out when we released 1.4.0 - 1.4.4, 1.4.5 was tested against it though

How have we done that in the past? Should we add it? I can open a PR.

**Comment by arschmitz** [comment]
@arthurvr we show latest so it should be added to the support list.

**Comment by arthurvr** [comment]
Correct me if I'm wrong but this was fixed in https://github.com/jquery/jquerymobile.com/commit/00a62f18b5ae23910cf617c5fe148085cb8114d7#diff-e7a1530caa373095af41ca24d477a28cR12 right?

**Comment by arschmitz** [comment]
@arthurvr ah forgot we had an issue for this when i updated support yes this is fixed
