### ISSUE TITLE
Internal Server Error 500 at Download

### ISSUE THREAD

**Issue by ucx** [jquery/jquerymobile.com#126]
jQuery Mobile Download Builder
Select branch
1.4.5
Core: Select all  
Events: Select all  
Forms: Select all  
Navigation: Select all  
Transitions: Select all  
Utilities: Select all  
Widgets: Select all  
--> Build my Download

**Comment by arthurvr** [comment]
I'm unable to reproduce this. Maybe something temporary. Can you re-try it?

**Comment by arschmitz** [comment]
@ucx I am also unable to reproduce. Can you try disabling any browser add ons you have they are known to cause issues.

**Comment by ucx** [comment]
yes I can,
Die Seite kann nicht angezeigt werden.   
   - Vergewissern Sie sich, dass die Webadresse http://amd-builder.jquerymobile.com  stimmt.
   - Suchen Sie die Seite mit Ihrer Suchmaschine.
   - Aktualisieren Sie die Seite in ein paar Minuten.

This is the german error message. Now it is 404 Error or 403 Error. 
The Build my Download link is not working for me. The Images link is okay withmouse right klick and save file. Yesterday I could download the jquerymobile zip at the Images Link.


 


     Alexander Schmitz <notifications@github.com> schrieb am 17:23 Samstag, 6.Juni 2015:
   

 @ucx I am also unable to reproduce. Can you try disabling any browser add ons you have they are known to cause issues. —

**Comment by arschmitz** [comment]
@ucx http://amd-builder.jquerymobile.com is an api endpoint it has never served html content the download builder is http://jquerymobile.com/download-builder/ where did you get that link?

**Comment by ucx** [comment]
this is the full link, I guess it is a false Header or any other error. I guess normally shouldthe download be open but it doesn't. Or you have a Limit at your Server. 

http://amd-builder.jquerymobile.com/v1/bundle/jquery/jquery-mobile/1.4.5/jquery.mobile.custom.zip?baseUrl=js&include=jquery.mobile.animationComplete%2Cjquery.mobile.data%2Cjquery.mobile.defaults%2Cjquery.mobile.helpers%2Cjquery.mobile.init%2Cjquery.mobile.ns%2Cjquery.mobile.support%2Cjquery.mobile.support.orientation%2Cjquery.mobile.support.touch%2Cjquery.mobile.vmouse%2Cjquery.mobile.widget%2Cwidgets%2Fpage%2Cevents%2Fnavigate%2Cevents%2Forientationchange%2Cevents%2Fthrottledresize%2Cevents%2Ftouch%2Cjquery.mobile.events%2Cjquery.mobile.buttonMarkup%2Cjquery.mobile.fieldContain%2Cwidgets%2Fcontrolgroup%2Cwidgets%2Fforms%2Fautogrow%2Cwidgets%2Fforms%2Fbutton%2Cwidgets%2Fforms%2Fcheckboxradio%2Cwidgets%2Fforms%2FclearButton%2Cwidgets%2Fforms%2Fflipswitch%2Cwidgets%2Fforms%2Frangeslider%2Cwidgets%2Fforms%2Freset%2Cwidgets%2Fforms%2Fselect%2Cwidgets%2Fforms%2Fselect.custom%2Cwidgets%2Fforms%2Fslider%2Cwidgets%2Fforms%2Fslider.tooltip%2Cwidgets%2Fforms%2Ftextinput%2Cjquery.mobile.navigation%2Cnavigation%2Fbase%2Cnavigation%2Fhistory%2Cnavigation%2Fmethod%2Cnavigation%2Fnavigator%2Cnavigation%2Fpath%2Cwidgets%2Fpagecontainer%2Ctransitions%2Fconcurrent%2Ctransitions%2Fhandlers%2Ctransitions%2Fserial%2Ctransitions%2Ftransition%2Ctransitions%2Fvisuals%2Ctransitions%2Fvisuals%2Fflip%2Ctransitions%2Fvisuals%2Fflow%2Ctransitions%2Fvisuals%2Fpop%2Ctransitions%2Fvisuals%2Fslide%2Ctransitions%2Fvisuals%2Fslidedown%2Ctransitions%2Fvisuals%2Fslidefade%2Ctransitions%2Fvisuals%2Fslideup%2Ctransitions%2Fvisuals%2Fturn%2Cjquery.mobile.degradeInputs%2Cjquery.mobile.links%2Cjquery.mobile.media%2Cjquery.mobile.nojs%2Cjquery.mobile.zoom%2Cjquery.mobile.zoom.iosorientationfix%2Cjquery.mobile.grid%2Cwidgets%2FaddFirstLastClasses%2Cwidgets%2Fcollapsible%2Cwidgets%2FcollapsibleSet%2Cwidgets%2Fdialog%2Cwidgets%2Ffilterable%2Cwidgets%2Ffilterable.backcompat%2Cwidgets%2FfixedToolbar%2Cwidgets%2FfixedToolbar.workarounds%2Cwidgets%2Flistview%2Cwidgets%2Flistview.autodividers%2Cwidgets%2Flistview.hidedividers%2Cwidgets%2Floader%2Cwidgets%2Fnavbar%2Cw 


     Alexander Schmitz <notifications@github.com> schrieb am 20:23 Samstag, 6.Juni 2015:
   

 @ucx http://amd-builder.jquerymobile.com is an api endpoint it has never served html content the download builder is http://jquerymobile.com/download-builder/ where did you get that link?—

**Comment by Krinkle** [comment]
Unable to reproduce this issue via <https://jquerymobile.com/download-builder/>.

I do note that the URL in the above comment by @ucx is incomplete. It is cut-off in the middle of a word "navbar,w" for "navbar,widgets", and missing several other query parameters as well. I can't tell whether that's due to it being broken in the process of copying to this comment or whether this is a separate bug from the one being reported here.

Feel free to file a new issue or leave a comment here with steps to reproduce the issue and the exact URL (as reported in the dev tools) where the problem happens.
