### ISSUE TITLE
Nginx version disclosure via forbidden Page

### ISSUE THREAD

**Issue by Sajibekanti** [jquery/jquerymobile.com#140]
Hello 
I am Sajibe Kanti 
I Have Found A Bug on your Web .

Vulnerability : Nginx version disclosure via forbidden Page

This information might help an attacker gain a greater understanding of the systems in use and potentially develop further attacks targeted at the specific version of Nginx.

Impact: 
An attacker might use the disclosed information to harvest specific security vulnerabilities for the version identified.

Steps to reproduce:

Go to http://jquerymobile.com/jquery-wp-content/themes/jquerymobile.com/i/

Now the nginx version shows in bottom.

Reference : https://hackerone.com/reports/194319

Thanks 
Sajibe Kanti

**Comment by mgol** [comment]
This is no longer exposed now.
