### ISSUE TITLE
build failure - 1.5.0-alpha.1

### ISSUE THREAD

**Issue by yotam-medini** [jquery/jquerymobile.com#141]
After selecting 1.5.0-alpha.1
Upon clicking: 
  "Build My Download"
nothing happens, and the browser console shows:
jquery-1.11.3.js:5761 GET http://amd-builder.jquerymobile.com/v1/bundle/jquery/jquery-mobile/1.5.0-al…on=true&filter=..%2Fbuild%2Ffilter&mainConfigFile=js%2Frequirejs.config.js 500 (Internal Server Error)

**Comment by mgol** [comment]
The Builder should work now.
