### ISSUE TITLE
Download Builder breaks when loaded over HTTPS

### ISSUE THREAD

**Issue by jammon** [jquery/jquerymobile.com#143]
You can select a branch, but the list of selectable parts doesn't appear.

The error message is:

    jquerymobile.com/:1 
    Mixed Content: The page at 'https://jquerymobile.com/download-builder/' was loaded
    over HTTPS, but requested an insecure script 
    'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js'. 
    This request has been blocked; the content must be served over HTTPS.

    jquery-1.11.3.js:9664 
    Mixed Content: The page at 'https://jquerymobile.com/download-builder/' was loaded 
    over HTTPS, but requested an insecure XMLHttpRequest endpoint 
    'http://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js'. 
    This request has been blocked; the content must be served over HTTPS.

**Comment by moloko** [comment]
Same here; just get the loading spinner going round round baby right round

![2017-07-06 14_39_40-jquery mobile download builder _ jquery mobile](https://user-images.githubusercontent.com/1249597/27913787-13d6b534-6259-11e7-9f6d-63677ca704c6.png)

Bit annoying when you have https-everywhere installed ;-)

**Comment by Pixelkracht** [comment]
This problem still exists today. Wouldn't have figured it out on my own. If this is hard to fix right now, perhaps some kind of warning could be posted on the download page, like "if you want to use this don't load over HTTPS" or something.
