### ISSUE TITLE
Console is showing

### ISSUE THREAD

**Issue by abhimanusharma** [jquery/jquerymobile.com#156]
Console is showing
jquery-1.11.3.js:9664 GET https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js 404 (Not Found)

and 

Access to XMLHttpRequest at 'https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js' from origin 'https://jquerymobile.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

_Originally posted by @abhimanusharma in https://github.com/jquery/jquerymobile.com/issues/71#issuecomment-508963317_

**Comment by mgol** [comment]
The Builder should work now.
