### ISSUE TITLE
version compatibility issue with jquery

### ISSUE THREAD

**Issue by abhimanusharma** [jquery/jquerymobile.com#157]
I am using jQuery version 1.12.4, jquery migrate ver=1.4.1, jquery mobile tried all available versions. 
jquery mobile events work fine but it disturbs the functionality of all other elements in the website like navigations menu (both mobile and desktop) do not work, sliders do not work.

I am getting this error in all the versions:
```
jquery-1.11.3.min.js:5 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

*and*

```
Uncaught TypeError: Cannot read property 'add' of null
    at c.b.initADA (eval at <anonymous> (jquery-1.11.3.min.js:2), <anonymous>:18:6683)
    at c.b.init (eval at <anonymous> (jquery-1.11.3.min.js:2), <anonymous>:17:18126)
```

After removing jquery mobile all functionality work fine but then mobile functionality does not work.

Jquery mobile builder is also not working at this movement so could not use specific event I want to use right now.

**Comment by mgol** [comment]
jQuery Mobile Download Builder should work at the moment. That said, jQuery Mobile itself is deprecated, see https://blog.jquerymobile.com/2021/10/07/jquery-maintainers-continue-modernization-initiative-with-deprecation-of-jquery-mobile/
