### ISSUE TITLE
Download Builder not opening

### ISSUE THREAD

**Issue by Crazydevil0** [jquery/jquerymobile.com#162]
The builder simply won't open, loader spinner keeps going on forever.
Main get fails because of CORS

`Access to XMLHttpRequest at 'https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js' from origin 'https://jquerymobile.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Colin-Fredericks** [comment]
Same here, on Firefox (71.0), Chrome (78.0.3904.108), and Safari (12.0, 14606.1.36.1.9) all on MacOS 10.14.

**Comment by d3n1c1d3** [comment]
Same for me on Chrome (79.0.3945.117) and Firefox (72.0.1) on Windows 10 Pro Version 1903

**Comment by bbeaulant** [comment]
Same problem :(

**Comment by byeze** [comment]
![image](https://user-images.githubusercontent.com/7424138/73479188-428d9b80-4376-11ea-9b5f-ab5329b768ea.png)
404 Not found on amd-builder.

**Comment by mgol** [comment]
The Builder should work now.
