### ISSUE TITLE
jquery mobile builder not working

### ISSUE THREAD

**Issue by ratchid** [jquery/jquerymobile.com#165]
Js error

Access to XMLHttpRequest at 'https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js' from origin 'https://jquerymobile.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js:1 Failed to load resource: net::ERR_FAILED

**Comment by mgol** [comment]
The Builder should work now.
