### ISSUE TITLE
He, seems to not load the custom jQuery mobile file generator

### ISSUE THREAD

**Issue by radukam** [jquery/jquerymobile.com#166]
He, seems to not load the custom jQuery mobile file generator.

URL:
https://jquerymobile.com/download-builder/

![print-s-error](https://user-images.githubusercontent.com/4904445/90333179-5b853380-dfcc-11ea-8c5b-e09382e3cb73.png)

**Comment by mgol** [comment]
The Builder should work now.

**Comment by radukam** [comment]
Great!
Thanks!





---------------------------------------

- Cu Stima!
- Kind Regards!
- Tiszteletem!

Giurgiu Radu
Web developer

E-mail: radukam@gmail.com
Skype id: radukam
Phone: 0040755273136
City: Cluj-Napoca
Web: http://equaltozero.ro

**Comment by gseguin** [comment]
Woohoo! Congrats @mgol on resurrecting that code!
