### ISSUE TITLE
Download Builder not loading

### ISSUE THREAD

**Issue by samdoidge** [jquery/jquerymobile.com#71]
Stuck on loading animation after selecting version

Console reports:
`XMLHttpRequest cannot load http://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.2/?baseUrl=js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jquerymobile.com' is therefore not allowed access.`

**Comment by abhimanusharma** [comment]
Console is showing
jquery-1.11.3.js:9664 GET https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js 404 (Not Found)

and 

Access to XMLHttpRequest at 'https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js' from origin 'https://jquerymobile.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
