### ISSUE TITLE
Add link to jquerymobile -> Resources -> Apps & frameworks

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquerymobile.com#98]
In https://github.com/jquery/jquery-mobile/issues/7596, @slavap wrote:
> Could you please add reference to jqm4gwt https://github.com/jqm4gwt/jqm4gwt into Apps&Frameworks section. It's Java/GWT wrapper over jQuery Mobile, so it's possible to develop apps using pure Java.

**Comment by arthurvr** [comment]
ping - what do we think about this one?

**Comment by slavap** [comment]
Almost one year to add simple link, I'm really impressed :-( There is nothing to think about, just add a link please. jqm4gwt is in well shape and quite useful for Java(GWT) developers.

**Comment by arthurvr** [comment]
@slavap You might want to PR it to push this forward? I wanted to do it but didn't find an icon.

**Comment by arthurvr** [comment]
My GWT isn't anything more then a todo app, but it does look handy :)

**Comment by arschmitz** [comment]
I'm fine with the change do agree a PR certainly speeds things up if anyone wants a link added to their framework or resource.

**Comment by slavap** [comment]
What are requirements for icon? 24x24?

**Comment by arthurvr** [comment]
@slavap We don't really have a strong requirement I think. I think 24x24 would be okay.

**Comment by slavap** [comment]
Ok, I've created 24x24 and 18x18 icons. If it's ok please add a link to jqm4gwt.
![jqm4gwt-24x24](https://cloud.githubusercontent.com/assets/4129763/7192234/8f027144-e448-11e4-80d7-1d1b76762163.png)
![jqm4gwt-18x18](https://cloud.githubusercontent.com/assets/4129763/7192237/94c89aa4-e448-11e4-8c64-046dcc555f05.png)
